/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BreakdownsRouteImport } from './routes/breakdowns'
import { Route as CalibrationRouteImport } from './routes/calibration'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as InspectionsRouteImport } from './routes/inspections'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LogbooksRouteImport } from './routes/logbooks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PmRouteImport } from './routes/pm'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as AssetsIdRouteImport } from './routes/assets.$id'
import { Route as BreakdownsIdRouteImport } from './routes/breakdowns.$id'
import { Route as BreakdownsNewRouteImport } from './routes/breakdowns.new'
import { Route as InspectionsIdRouteImport } from './routes/inspections.$id'
import { Route as WorkOrdersIdRouteImport } from './routes/work-orders.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakdownsRoute = BreakdownsRouteImport.update({
  id: '/breakdowns',
  path: '/breakdowns',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrationRoute = CalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsRoute = InspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogbooksRoute = LogbooksRouteImport.update({
  id: '/logbooks',
  path: '/logbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PmRoute = PmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssetsRoute,
} as any)
const BreakdownsIdRoute = BreakdownsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BreakdownsRoute,
} as any)
const BreakdownsNewRoute = BreakdownsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BreakdownsRoute,
} as any)
const InspectionsIdRoute = InspectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InspectionsRoute,
} as any)
const WorkOrdersIdRoute = WorkOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkOrdersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/breakdowns': typeof BreakdownsRouteWithChildren
  '/calibration': typeof CalibrationRoute
  '/contracts': typeof ContractsRoute
  '/documents': typeof DocumentsRoute
  '/housekeeping': typeof HousekeepingRoute
  '/incidents': typeof IncidentsRoute
  '/inspections': typeof InspectionsRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/logbooks': typeof LogbooksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pm': typeof PmRoute
  '/reports': typeof ReportsRoute
  '/safety': typeof SafetyRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/utilities': typeof UtilitiesRoute
  '/vendors': typeof VendorsRoute
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/assets/$id': typeof AssetsIdRoute
  '/breakdowns/$id': typeof BreakdownsIdRoute
  '/breakdowns/new': typeof BreakdownsNewRoute
  '/inspections/$id': typeof InspectionsIdRoute
  '/work-orders/$id': typeof WorkOrdersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/breakdowns': typeof BreakdownsRouteWithChildren
  '/calibration': typeof CalibrationRoute
  '/contracts': typeof ContractsRoute
  '/documents': typeof DocumentsRoute
  '/housekeeping': typeof HousekeepingRoute
  '/incidents': typeof IncidentsRoute
  '/inspections': typeof InspectionsRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/logbooks': typeof LogbooksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pm': typeof PmRoute
  '/reports': typeof ReportsRoute
  '/safety': typeof SafetyRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/utilities': typeof UtilitiesRoute
  '/vendors': typeof VendorsRoute
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/assets/$id': typeof AssetsIdRoute
  '/breakdowns/$id': typeof BreakdownsIdRoute
  '/breakdowns/new': typeof BreakdownsNewRoute
  '/inspections/$id': typeof InspectionsIdRoute
  '/work-orders/$id': typeof WorkOrdersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/breakdowns': typeof BreakdownsRouteWithChildren
  '/calibration': typeof CalibrationRoute
  '/contracts': typeof ContractsRoute
  '/documents': typeof DocumentsRoute
  '/housekeeping': typeof HousekeepingRoute
  '/incidents': typeof IncidentsRoute
  '/inspections': typeof InspectionsRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/logbooks': typeof LogbooksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pm': typeof PmRoute
  '/reports': typeof ReportsRoute
  '/safety': typeof SafetyRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/utilities': typeof UtilitiesRoute
  '/vendors': typeof VendorsRoute
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/assets/$id': typeof AssetsIdRoute
  '/breakdowns/$id': typeof BreakdownsIdRoute
  '/breakdowns/new': typeof BreakdownsNewRoute
  '/inspections/$id': typeof InspectionsIdRoute
  '/work-orders/$id': typeof WorkOrdersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/breakdowns'
    | '/calibration'
    | '/contracts'
    | '/documents'
    | '/housekeeping'
    | '/incidents'
    | '/inspections'
    | '/inventory'
    | '/logbooks'
    | '/login'
    | '/notifications'
    | '/pm'
    | '/reports'
    | '/safety'
    | '/scan'
    | '/search'
    | '/settings'
    | '/utilities'
    | '/vendors'
    | '/work-orders'
    | '/assets/$id'
    | '/breakdowns/$id'
    | '/breakdowns/new'
    | '/inspections/$id'
    | '/work-orders/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/breakdowns'
    | '/calibration'
    | '/contracts'
    | '/documents'
    | '/housekeeping'
    | '/incidents'
    | '/inspections'
    | '/inventory'
    | '/logbooks'
    | '/login'
    | '/notifications'
    | '/pm'
    | '/reports'
    | '/safety'
    | '/scan'
    | '/search'
    | '/settings'
    | '/utilities'
    | '/vendors'
    | '/work-orders'
    | '/assets/$id'
    | '/breakdowns/$id'
    | '/breakdowns/new'
    | '/inspections/$id'
    | '/work-orders/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/breakdowns'
    | '/calibration'
    | '/contracts'
    | '/documents'
    | '/housekeeping'
    | '/incidents'
    | '/inspections'
    | '/inventory'
    | '/logbooks'
    | '/login'
    | '/notifications'
    | '/pm'
    | '/reports'
    | '/safety'
    | '/scan'
    | '/search'
    | '/settings'
    | '/utilities'
    | '/vendors'
    | '/work-orders'
    | '/assets/$id'
    | '/breakdowns/$id'
    | '/breakdowns/new'
    | '/inspections/$id'
    | '/work-orders/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  BreakdownsRoute: typeof BreakdownsRouteWithChildren
  CalibrationRoute: typeof CalibrationRoute
  ContractsRoute: typeof ContractsRoute
  DocumentsRoute: typeof DocumentsRoute
  HousekeepingRoute: typeof HousekeepingRoute
  IncidentsRoute: typeof IncidentsRoute
  InspectionsRoute: typeof InspectionsRouteWithChildren
  InventoryRoute: typeof InventoryRoute
  LogbooksRoute: typeof LogbooksRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PmRoute: typeof PmRoute
  ReportsRoute: typeof ReportsRoute
  SafetyRoute: typeof SafetyRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  UtilitiesRoute: typeof UtilitiesRoute
  VendorsRoute: typeof VendorsRoute
  WorkOrdersRoute: typeof WorkOrdersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breakdowns': {
      id: '/breakdowns'
      path: '/breakdowns'
      fullPath: '/breakdowns'
      preLoaderRoute: typeof BreakdownsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibration': {
      id: '/calibration'
      path: '/calibration'
      fullPath: '/calibration'
      preLoaderRoute: typeof CalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections': {
      id: '/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof InspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logbooks': {
      id: '/logbooks'
      path: '/logbooks'
      fullPath: '/logbooks'
      preLoaderRoute: typeof LogbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pm': {
      id: '/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof PmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$id': {
      id: '/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/breakdowns/$id': {
      id: '/breakdowns/$id'
      path: '/$id'
      fullPath: '/breakdowns/$id'
      preLoaderRoute: typeof BreakdownsIdRouteImport
      parentRoute: typeof BreakdownsRoute
    }
    '/breakdowns/new': {
      id: '/breakdowns/new'
      path: '/new'
      fullPath: '/breakdowns/new'
      preLoaderRoute: typeof BreakdownsNewRouteImport
      parentRoute: typeof BreakdownsRoute
    }
    '/inspections/$id': {
      id: '/inspections/$id'
      path: '/$id'
      fullPath: '/inspections/$id'
      preLoaderRoute: typeof InspectionsIdRouteImport
      parentRoute: typeof InspectionsRoute
    }
    '/work-orders/$id': {
      id: '/work-orders/$id'
      path: '/$id'
      fullPath: '/work-orders/$id'
      preLoaderRoute: typeof WorkOrdersIdRouteImport
      parentRoute: typeof WorkOrdersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssetsRouteChildren {
  AssetsIdRoute: typeof AssetsIdRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsIdRoute: AssetsIdRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface BreakdownsRouteChildren {
  BreakdownsIdRoute: typeof BreakdownsIdRoute
  BreakdownsNewRoute: typeof BreakdownsNewRoute
}

const BreakdownsRouteChildren: BreakdownsRouteChildren = {
  BreakdownsIdRoute: BreakdownsIdRoute,
  BreakdownsNewRoute: BreakdownsNewRoute,
}

const BreakdownsRouteWithChildren = BreakdownsRoute._addFileChildren(
  BreakdownsRouteChildren,
)

interface InspectionsRouteChildren {
  InspectionsIdRoute: typeof InspectionsIdRoute
}

const InspectionsRouteChildren: InspectionsRouteChildren = {
  InspectionsIdRoute: InspectionsIdRoute,
}

const InspectionsRouteWithChildren = InspectionsRoute._addFileChildren(
  InspectionsRouteChildren,
)

interface WorkOrdersRouteChildren {
  WorkOrdersIdRoute: typeof WorkOrdersIdRoute
}

const WorkOrdersRouteChildren: WorkOrdersRouteChildren = {
  WorkOrdersIdRoute: WorkOrdersIdRoute,
}

const WorkOrdersRouteWithChildren = WorkOrdersRoute._addFileChildren(
  WorkOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRouteWithChildren,
  BreakdownsRoute: BreakdownsRouteWithChildren,
  CalibrationRoute: CalibrationRoute,
  ContractsRoute: ContractsRoute,
  DocumentsRoute: DocumentsRoute,
  HousekeepingRoute: HousekeepingRoute,
  IncidentsRoute: IncidentsRoute,
  InspectionsRoute: InspectionsRouteWithChildren,
  InventoryRoute: InventoryRoute,
  LogbooksRoute: LogbooksRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PmRoute: PmRoute,
  ReportsRoute: ReportsRoute,
  SafetyRoute: SafetyRoute,
  ScanRoute: ScanRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  UtilitiesRoute: UtilitiesRoute,
  VendorsRoute: VendorsRoute,
  WorkOrdersRoute: WorkOrdersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
